name: New Push
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Begin Tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      # - name: Setup
      #   uses: actions/checkout@v1
      - name: npm install
        run: |
          npm install
          npm run build --if-present

      - name: Run Tests
        run: npm test